# Generated by Django 4.2.2 on 2023-06-06 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userinfo',
            old_name='department_ID',
            new_name='department',
        ),
    ]
