# Generated by Django 4.2.2 on 2023-06-07 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0002_rename_department_id_userinfo_department'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userinfo',
            old_name='account',
            new_name='account_balance',
        ),
    ]
