# Generated by Django 4.2.2 on 2023-06-11 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0005_alter_userinfo_create_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='create_time',
            field=models.CharField(max_length=16, verbose_name='create_time'),
        ),
    ]
